export enum PermissionAction {
  REQUEST = 'request',
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
}

export enum PermissionResource {
  USER = 'User',
  BUSINESS = 'Business',
  ROLE = 'Role',
  FEATURE = 'Feature',
  PERMISSION = 'Permission',
  SUBSCRIPTION_PLAN = 'Subscription Plan',
  BUSINESS_SUBSCRIPTION = 'BusinessSubscription',
  EMPLOYMENT_STATUS = 'Employment Status',
  DESIGNATION = 'Designation',
  WORK_SITE = 'Work Site',
  WORK_SCHEDULE = 'Work Schedule',
  DEPARTMENT = 'Department',
  LEAVE_TYPE = 'Leave Type',
  ASSET_TYPE = 'Asset Type',
  ASSET = 'Asset',
  PROJECT = 'Project',
  PROJECT_MEMBER = 'Project Member',
  ATTENDANCE_SETTINGS = 'Attendance Settings',
  LEAVE_SETTINGS = 'Leave Settings',
  BUSINESS_SETTINGS = 'Business Settings',
  DOCUMENT = 'Document',
  NOTE = 'Note',
  SOCIAL_LINK = 'Social Link',
  ATTENDANCE = 'Attendance',
  LEAVE = 'Leave',
  HOLIDAY = 'Holiday',
  PAYROLL_COMPONENT = 'Payroll Component',
  PAYROLL_ADJUSTMENT = 'Payroll Adjustment',
  PAYROLL = 'Payroll',
  PAYROLL_CYCLE = 'Payroll Cycle',
  PAYROLL_ITEM = 'Payroll Item',
  SALARY = 'Salary',
  PROFILE = 'Profile',
  EDUCATION_HISTORY = 'Education History',
  JOB_HISTORY = 'Job History',
  EMERGENCY_CONTACT = 'Emergency Contact',
  EMPLOYMENT_DETAILS = 'Employment Details',
  NOTIFICATION = 'Notification',
  NOTIFICATION_TEMPLATE = 'Notification Template',
}
