export enum PermissionAction {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
}

export enum PermissionResource {
  USER = 'User',
  BUSINESS = 'Business',
  ROLE = 'Role',
  FEATURE = 'Feature',
  PERMISSION = 'Permission',
  SUBSCRIPTION_PLAN = 'Subscription Plan',
  EMPLOYMENT_STATUS = 'Employment Status',
  DESIGNATION = 'Designation',
  JOB_TYPE = 'Job Type',
  JOB_PLATFORM = 'Job Platform',
  RECRUITMENT_PROCESS = 'Recruitment Process',
  ONBOARDING_PROCESS = 'Onboarding Process',
  WORK_SITE = 'Work Site',
  WORK_SCHEDULE = 'Work Schedule',
  DEPARTMENT = 'Department',
  LEAVE_TYPE = 'Leave Type',
  ASSET_TYPE = 'Asset Type',
  ASSET = 'Asset',
  PROJECT = 'Project',
  PROJECT_MEMBER = 'Project Member',
  ATTENDANCE_SETTINGS = 'Attendance Settings',
  LEAVE_SETTINGS = 'Leave Settings',
  BUSINESS_SETTINGS = 'Business Settings',
  DOCUMENT = 'Document',
  NOTE = 'Note',
  SOCIAL_LINK = 'Social Link',
}
