export const subscriptionPlans = [
  {
    name: 'Starter',
    description: 'Starter plan with basic features',
    price: 50,
    setupFee: 5,
    status: 'ACTIVE',
  },
  {
    name: 'Standard',
    description: 'Standard plan for small businesses',
    price: 120,
    setupFee: 15,
    status: 'ACTIVE',
  },
  {
    name: 'Pro',
    description: 'Pro plan with advanced analytics',
    price: 250,
    setupFee: 25,
    status: 'INACTIVE',
  },
  {
    name: 'Enterprise',
    description: 'Enterprise-level subscription',
    price: 500,
    setupFee: 50,
    status: 'ACTIVE',
  },
  {
    name: 'Trial',
    description: 'Trial plan with limited access',
    price: 0,
    setupFee: 0,
    status: 'ACTIVE',
  },
  {
    name: 'Basic Annual',
    description: 'Basic annual subscription',
    price: 900,
    setupFee: 20,
    status: 'INACTIVE',
  },
  {
    name: 'Premium',
    description: 'Premium subscription with extras',
    price: 350,
    setupFee: 30,
    status: 'ACTIVE',
  },
  {
    name: 'Team',
    description: 'Team plan with multi-user access',
    price: 400,
    setupFee: 40,
    status: 'INACTIVE',
  },
  {
    name: 'Student',
    description: 'Student plan with discount',
    price: 30,
    setupFee: 5,
    status: 'ACTIVE',
  },
  {
    name: 'Custom',
    description: 'Custom plan for enterprises',
    price: 1000,
    setupFee: 100,
    status: 'ACTIVE',
  },
];
